services:
  api:
    build:
      dockerfile: dockerfiles/services/api/Dockerfile.dev
      context: .
    volumes:
      - ./src:/workspace/src
      - ./readme.md:/workspace/readme.md
      - ./log:/workspace/log
    command: [ "uvicorn", "--port", "8000", "--host", "0.0.0.0", "--reload", "src.api:app" ]

  docs:
    build:
      dockerfile: dockerfiles/services/docs/Dockerfile.dev
      context: .
    volumes:
      - ./docs:/workspace/docs
      - ./mkdocs.yml:/workspace/mkdocs.yml
      - ./.git:/workspace/.git
    networks:
      - public
    command: ["mkdocs", "serve", "--dev-addr", "0.0.0.0:8080"]

  server:
    image: nginx:1.21
    depends_on:
      - docs
    volumes:
      - ./dockerfiles/services/server/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dockerfiles/services/server/nginx.conf.dev:/etc/nginx/extends/dev.conf

  admin:
    image: adminer
    networks:
      - db
      - public
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    ports:
      - 8080:8080
